# Pandas

## Завдання 1
У вас є дані про книги з полями: "Назва", "Автор", "Рік видання", "Ціна".

- Створіть DataFrame з не менш ніж шістьма рядками.
- Виведіть увесь DataFrame.
- Визначте середню ціну книг.
- Знайдіть книги, видані після 2015 року.
- Відсортуйте DataFrame за ціною в порядку зростання.

In [8]:
import pandas as pd
import numpy as np

In [ ]:
# Створіть DataFrame з не менш ніж шістьма рядками.
# Виведіть увесь DataFrame.
data = {
    "Title": [
        "1984",
        "Dune",
        "The Hobbit",
        "Harry Potter",
        "The Martian",
        "The Witcher"
    ],
    "Author": [
        "George Orwell",
        "Frank Herbert",
        "J.R.R. Tolkien",
        "J.K. Rowling",
        "Andy Weir",
        "Andrzej Sapkowski"
    ],
    "Year": [
        1949,
        1965,
        1937,
        1997,
        2011,
        1993
    ],
    "Price": [
        15.99,
        20.50,
        12.75,
        18.00,
        16.40,
        14.30
    ]
}
books = pd.DataFrame(data)
books

In [13]:
# Визначте середню ціну книг.
np.mean(books['Price'])

np.float64(16.323333333333334)

In [19]:
# Знайдіть книги, видані після 2015 року.
books[books["Year"] > 2015]

Empty DataFrame
Columns: [Title, Author, Year, Price]
Index: []

In [21]:
# Відсортуйте DataFrame за ціною в порядку зростання.
books.sort_values(by="Price", ascending=False)

          Title             Author  Year  Price
1          Dune      Frank Herbert  1965  20.50
3  Harry Potter       J.K. Rowling  1997  18.00
4   The Martian          Andy Weir  2011  16.40
0          1984      George Orwell  1949  15.99
5   The Witcher  Andrzej Sapkowski  1993  14.30
2    The Hobbit     J.R.R. Tolkien  1937  12.75

## Завдання 2
У CSV-файлі містяться дані про замовлення: "Номер замовлення", "Клієнт", "Дата", "Сума".

- Прочитайте дані з файлу в DataFrame.
- Виведіть перші десять рядків
- Визначте кількість замовлень кожного клієнта.
- Знайдіть максимальну та мінімальну суми замовлень.
- Підрахуйте загальну суму всіх замовлень.

In [26]:
# Прочитайте дані з файлу в DataFrame.
orders = pd.read_csv("orders.csv")

In [29]:
# Виведіть перші десять рядків
orders.head(10)

   Order Number         Customer        Date  Amount
0          1001       John Smith  2026-07-01  125.50
1          1002    Emily Johnson  2026-07-02   89.99
2          1003    Michael Brown  2026-07-03  234.75
3          1004      Sarah Davis  2026-07-04  560.20
4          1005     David Wilson  2026-07-05  178.00
5          1006   Jessica Miller  2026-07-06  320.50
6          1007  Daniel Anderson  2026-07-07   95.25
7          1008    Olivia Taylor  2026-07-08  145.00
8          1009     James Thomas  2026-07-09  780.99
9          1010        Ava Moore  2026-07-10  450.50

In [31]:
# Визначте кількість замовлень кожного клієнта.
CustomerOrdersCount = orders["Customer"].value_counts()
CustomerOrdersCount

Customer
John Smith             1
Emily Johnson          1
Michael Brown          1
Sarah Davis            1
David Wilson           1
Jessica Miller         1
Daniel Anderson        1
Olivia Taylor          1
James Thomas           1
Ava Moore              1
Robert Jackson         1
Emma White             1
William Harris         1
Sophia Martin          1
Joseph Thompson        1
Isabella Garcia        1
Thomas Martinez        1
Mia Robinson           1
Charles Clark          1
Charlotte Rodriguez    1
Christopher Lewis      1
Amelia Lee             1
Matthew Walker         1
Harper Hall            1
Anthony Allen          1
Evelyn Young           1
Mark Hernandez         1
Abigail King           1
Steven Wright          1
Ella Lopez             1
Name: count, dtype: int64

In [36]:
# Знайдіть максимальну та мінімальну суми замовлень.
print("Min:", min(orders["Amount"]))
print("Max:", max(orders["Amount"]))

Min: 67.8
Max: 2150.99

In [37]:
# Підрахуйте загальну суму всіх замовлень.
print(sum(orders["Amount"]))

16430.6

## Завдання 3
Є таблиця з даними про продукти харчування: "Продукт", "Категорія", "Калорії", "Білки".

- Створіть DataFrame з не менш ніж десятьма рядками.
- Виведіть увесь DataFrame.
- Знайдіть усі продукти з калорійністю вище 300.
- Підрахуйте середню кількість білків за категоріями.
- Відсортуйте DataFrame за калорійністю в порядку убування.

In [41]:
# Створіть DataFrame з не менш ніж десятьма рядками.
# Виведіть увесь DataFrame.
data = {
    "Product": [
        "Chicken Breast",
        "Rice",
        "Eggs",
        "Salmon",
        "Banana",
        "Apple",
        "Broccoli",
        "Potato",
        "Greek Yogurt",
        "Oatmeal",
        "Almonds",
        "Avocado"
    ],
    "Category": [
        "Meat",
        "Grains",
        "Dairy",
        "Fish",
        "Fruit",
        "Fruit",
        "Vegetables",
        "Vegetables",
        "Dairy",
        "Grains",
        "Nuts",
        "Fruit"
    ],
    "Calories": [
        165,
        130,
        155,
        208,
        89,
        52,
        34,
        77,
        59,
        68,
        579,
        160
    ],
    "Protein": [
        31,
        2.7,
        13,
        20,
        1.1,
        0.3,
        2.8,
        2,
        10,
        2.4,
        21,
        2
    ]
}

foods = pd.DataFrame(data)
foods

           Product    Category  Calories  Protein
0   Chicken Breast        Meat       165     31.0
1             Rice      Grains       130      2.7
2             Eggs       Dairy       155     13.0
3           Salmon        Fish       208     20.0
4           Banana       Fruit        89      1.1
5            Apple       Fruit        52      0.3
6         Broccoli  Vegetables        34      2.8
7           Potato  Vegetables        77      2.0
8     Greek Yogurt       Dairy        59     10.0
9          Oatmeal      Grains        68      2.4
10         Almonds        Nuts       579     21.0
11         Avocado       Fruit       160      2.0

In [42]:
# Знайдіть усі продукти з калорійністю вище 300.
foods[foods["Calories"] > 300]

    Product Category  Calories  Protein
10  Almonds     Nuts       579     21.0

In [47]:
# Підрахуйте середню кількість білків за категоріями.
foods.groupby("Category")["Protein"].mean()

Category
Dairy         11.500000
Fish          20.000000
Fruit          1.133333
Grains         2.550000
Meat          31.000000
Nuts          21.000000
Vegetables     2.400000
Name: Protein, dtype: float64

In [49]:
# Відсортуйте DataFrame за калорійністю в порядку убування.
foods.sort_values(by="Calories", ascending=True)

           Product    Category  Calories  Protein
6         Broccoli  Vegetables        34      2.8
5            Apple       Fruit        52      0.3
8     Greek Yogurt       Dairy        59     10.0
9          Oatmeal      Grains        68      2.4
7           Potato  Vegetables        77      2.0
4           Banana       Fruit        89      1.1
1             Rice      Grains       130      2.7
2             Eggs       Dairy       155     13.0
11         Avocado       Fruit       160      2.0
0   Chicken Breast        Meat       165     31.0
3           Salmon        Fish       208     20.0
10         Almonds        Nuts       579     21.0

## Завдання 4
Зібрано дані про співробітників та їхні проекти: "Ім'я", "Проект", "Години".

- Створіть DataFrame з не менш ніж вісьмома рядками.
- Виведіть вихідний DataFrame.
- Підрахуйте загальну кількість годин за кожним співробітником.
- Підрахуйте загальну кількість годин за кожним проектом.
- Знайдіть співробітника, який витратив найбільше годин.

In [52]:
# Створіть DataFrame з не менш ніж вісьмома рядками.
# Виведіть вихідний DataFrame.
data = {
    "Name": [
        "John Smith",
        "Emily Johnson",
        "Michael Brown",
        "Sarah Davis",
        "David Wilson",
        "Jessica Miller",
        "Daniel Anderson",
        "Olivia Taylor",
        "James Thomas",
        "Sophia Martin"
    ],
    "Project": [
        "Website",
        "Mobile App",
        "Website",
        "Database",
        "Mobile App",
        "API Development",
        "Database",
        "Website",
        "API Development",
        "Mobile App"
    ],
    "Hours": [
        32,
        28,
        40,
        24,
        35,
        30,
        26,
        38,
        22,
        34
    ]
}


employees = pd.DataFrame(data)
employees

              Name          Project  Hours
0       John Smith          Website     32
1    Emily Johnson       Mobile App     28
2    Michael Brown          Website     40
3      Sarah Davis         Database     24
4     David Wilson       Mobile App     35
5   Jessica Miller  API Development     30
6  Daniel Anderson         Database     26
7    Olivia Taylor          Website     38
8     James Thomas  API Development     22
9    Sophia Martin       Mobile App     34

In [55]:
# Підрахуйте загальну кількість годин за кожним співробітником.
employees.groupby("Name")["Hours"].sum()

Name
Daniel Anderson    26
David Wilson       35
Emily Johnson      28
James Thomas       22
Jessica Miller     30
John Smith         32
Michael Brown      40
Olivia Taylor      38
Sarah Davis        24
Sophia Martin      34
Name: Hours, dtype: int64

In [56]:
# Підрахуйте загальну кількість годин за кожним проектом.
employees.groupby("Project")["Hours"].sum()

Project
API Development     52
Database            50
Mobile App          97
Website            110
Name: Hours, dtype: int64

In [58]:
# Знайдіть співробітника, який витратив найбільше годин.
employees.groupby("Name")["Hours"].sum().max()

np.int64(40)

## Завдання 5
У вас є таблиця продажів квитків: "Фільм", "Місто", "Продані квитки".

- Створіть DataFrame з не менш ніж дванадцятьма рядками.
- Виведіть увесь DataFrame.
- Підрахуйте загальну кількість проданих квитків за кожним фільмом.
- Підрахуйте загальну кількість квитків по кожному місту.
- Знайдіть фільм із найбільшою кількістю продажів.

In [59]:
#
#
data = {
    "Movie": [
        "Avengers",
        "Avatar",
        "Inception",
        "The Batman",
        "Interstellar",
        "Oppenheimer",
        "Avengers",
        "Avatar",
        "Inception",
        "The Batman",
        "Interstellar",
        "Oppenheimer"
    ],
    "City": [
        "New York",
        "London",
        "Berlin",
        "Prague",
        "Paris",
        "Warsaw",
        "London",
        "Berlin",
        "Prague",
        "Paris",
        "Warsaw",
        "New York"
    ],
    "Tickets Sold": [
        1250,
        980,
        750,
        1100,
        1350,
        920,
        1150,
        870,
        680,
        1050,
        1200,
        890
    ]
}


tickets = pd.DataFrame(data)
tickets

           Movie      City  Tickets Sold
0       Avengers  New York          1250
1         Avatar    London           980
2      Inception    Berlin           750
3     The Batman    Prague          1100
4   Interstellar     Paris          1350
5    Oppenheimer    Warsaw           920
6       Avengers    London          1150
7         Avatar    Berlin           870
8      Inception    Prague           680
9     The Batman     Paris          1050
10  Interstellar    Warsaw          1200
11   Oppenheimer  New York           890

In [63]:
# Підрахуйте загальну кількість проданих квитків за кожним фільмом.
tickets.groupby("Movie")["Tickets Sold"].sum()

Movie
Avatar          1850
Avengers        2400
Inception       1430
Interstellar    2550
Oppenheimer     1810
The Batman      2150
Name: Tickets Sold, dtype: int64

In [67]:
# Підрахуйте загальну кількість квитків по кожному місту.
tickets.groupby("City")["Tickets Sold"].sum()

City
Berlin      1620
London      2130
New York    2140
Paris       2400
Prague      1780
Warsaw      2120
Name: Tickets Sold, dtype: int64

In [66]:
# Знайдіть фільм із найбільшою кількістю продажів.
tickets.groupby("Movie")["Tickets Sold"].sum().max()

np.int64(2550)

# Завдання 6
Дано дві таблиці: перша з інформацією про клієнтів ("ID", "Ім'я", "Місто"), друга — з їхніми замовленнями ("ID клієнта", "Замовлення", "Вартість").

- Створіть два DataFrame і заповніть їх не менш ніж п'ятьма рядками кожен.
- Виведіть обидва DataFrame.
- Об'єднайте їх за ідентифікатором клієнта.
- Підрахуйте загальну вартість замовлень за кожним клієнтом.
- Виведіть результат у вигляді нового DataFrame.

In [68]:
data1 = {
    "ID": [1, 2, 3, 4, 5, 6],
    "Name": [
        "John Smith",
        "Emily Johnson",
        "Michael Brown",
        "Sarah Davis",
        "David Wilson",
        "Jessica Miller"
    ],
    "City": [
        "New York",
        "London",
        "Berlin",
        "Prague",
        "Paris",
        "Warsaw"
    ]
}

data2 = {
    "Customer ID": [1, 2, 1, 4, 5, 3],
    "Order": [
        "Laptop",
        "Headphones",
        "Keyboard",
        "Monitor",
        "Mouse",
        "Webcam"
    ],
    "Value": [
        1200.00,
        150.50,
        75.99,
        340.00,
        45.50,
        89.99
    ]
}

customers = pd.DataFrame(data1)
orders = pd.DataFrame(data2)

print(customers)
print(orders)

   ID            Name      City
0   1      John Smith  New York
1   2   Emily Johnson    London
2   3   Michael Brown    Berlin
3   4     Sarah Davis    Prague
4   5    David Wilson     Paris
5   6  Jessica Miller    Warsaw
   Customer ID       Order    Value
0            1      Laptop  1200.00
1            2  Headphones   150.50
2            1    Keyboard    75.99
3            4     Monitor   340.00
4            5       Mouse    45.50
5            3      Webcam    89.99

In [72]:
# Об'єднайте їх за ідентифікатором клієнта.
merged = pd.merge(
    customers,
    orders,
    left_on="ID",
    right_on="Customer ID",
    how="inner"
)
merged

   ID           Name      City  Customer ID       Order    Value
0   1     John Smith  New York            1      Laptop  1200.00
1   1     John Smith  New York            1    Keyboard    75.99
2   5   David Wilson     Paris            5       Mouse    45.50
3   2  Emily Johnson    London            2  Headphones   150.50
4   4    Sarah Davis    Prague            4     Monitor   340.00
5   3  Michael Brown    Berlin            3      Webcam    89.99

In [74]:
# Підрахуйте загальну вартість замовлень за кожним клієнтом.
merged.groupby("Name")["Value"].sum()

Name
David Wilson       45.50
Emily Johnson     150.50
John Smith       1275.99
Michael Brown      89.99
Sarah Davis       340.00
Name: Value, dtype: float64

In [76]:
# Виведіть результат у вигляді нового DataFrame.
pd.DataFrame(merged.groupby("Name")["Value"].sum())

                 Value
Name
David Wilson     45.50
Emily Johnson   150.50
John Smith     1275.99
Michael Brown    89.99
Sarah Davis     340.00